### ISSUE TITLE
Count KMCProcess events

### ISSUE THREAD

**Issue by millskyle** [leetmaa/KMCLib#19]
I've read through the documentation and I can't figure out how to count the number of times an event fires without printing the trajectory information or launching an analysis plugin after every step.  Is there a way to print/record a running tally of how many times an event type has been fired?

**Comment by leetmaa** [comment]
It's been a while since I looked at this (and since you asked the question also indeed), but to give you an answer:

The information you are looking for is stored on the configuration in C++ for the latest fired event. Check configuration.cpp L275-277. This object is accessible from python so a custom analyzer should do the trick. If that's too slow for you you'll have to store the statistics you're looking for in C++ directly.
