### ISSUE TITLE
python-dev / Python.h 

### ISSUE THREAD

**Issue by tomswinburne** [leetmaa/KMCLib#21]
Hello,

Just a quick comment regarding installation on ubuntu 18.04.
For the final make (make test.x worked fine) Python.h wasn't found.

Solution:
sudo apt install python-dev
locate Python.h # find where it is
in CMakeLists.txt:
include_directories(where_it_is)

Thanks for making this available

**Comment by ChillyWillux** [comment]
Hello, 

I'm trying to install KMCLib on Ubuntu 18.04, however I'm confronting an error during the make test.x step. 
I get this message 

/home/chilly_willux/KMCLib-2.0-a1/c++/unittest/test_interactions.cpp:146:25: error: the compiler can assume that the address of ‘rc’ will never be NULL [-Werror=address]
     CPPUNIT_ASSERT( &rc != NULL );

Do you think it has a relation with your ancient issue ? 
Because I tried to follow your solution, I'm not sure in which CMakeLists.txt I have to include the directories. Is it the one in the /KMCLib/c++ folder or the other ones ? 

Thanks for your answer

**Comment by leetmaa** [comment]
@ChillyWillux the assert statement checks that the address of rc differs from NULL. Now apparently your compiler has already figured out that it cannot be NULL and it therefore refuses to compile. It should be safe to delete the assert statement.

What platform and compiler are you using?

**Comment by leetmaa** [comment]
@tomswinburne Yes, your compiler must know the location of the correct Python.h file. One way to do it is through the CMakeLists.txt file as you mention. Another way is to put the Python headers in your CPLUS_INCLUDE_PATH. It's mentioned briefly in the install section of the manual http://leetmaa.github.io/KMCLib/manual-v1.1/install.html

**Comment by ChillyWillux** [comment]
@leetmaa I delete the assert statement and it helps because now i'm facing a new error which is 
/home/chilly_willux/KMCLib-2.0-a1/c++/src/hash.cpp:19:10: fatal error: externals/md5.h: No such file or directory
 #include "externals/md5.h"
So I tried to locate this md5.h file however there are several of them so I don't know which one I have to copy into the folder /externals 

I'm usually writting my algorithm with spyder (I'm not sure that you meant that by plateform) and my compilers are g++ and gcc in their newest version

**Comment by leetmaa** [comment]
Have a look at the installation guide here: http://leetmaa.github.io/KMCLib/manual-v1.1/install.html#build-the-externals
